const ENV = {
  API_BASE_URL:
    process.env.NEXT_PUBLIC_API_BASE_URL,
  TOKEN_ENDPOINT:
    process.env.NEXT_PUBLIC_TOKEN_ENDPOINT,
  CURRENT_USER_ENDPOINT:
    process.env.NEXT_PUBLIC_CURRENT_USER_ENDPOINT,
  TENANTS_ENDPOINT:
    process.env.NEXT_PUBLIC_TENANTS_ENDPOINT,
  REGISTER_ENDPOINT:
    process.env.NEXT_PUBLIC_REGISTER_ENDPOINT,
} as const;

export default ENV;
